# Generated by Django 5.1 on 2024-09-09 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facture', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='saved_by',
        ),
    ]
